## Change these first
owner: assafdori # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: ASSAFDORI.COM
    url: https://www.assafdori.com

status-website:
  cname: status.assafdori.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ASSAF DORI - PRODUCTION
  introTitle: "**ASSAFDORI.COM** is monitored by Upptime, open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a live status page which uses **real-time** data from my [GitHub repository](https://github.com/assafdori/up).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
