## Change these first
owner: assafdori # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: ROOT
    url: https://assafdori.com
  - name: WWW
    url: https://www.assafdori.com

status-website:
  cname: status.assafdori.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: PRODUCTION ENVIRONMENT
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a live status page which uses **real-time** data from my repository [GitHub repository](https://github.com/assafdori/up).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
